### ISSUE TITLE
Misleading link on crates.io/docs.rs

### ISSUE THREAD

**Issue by Mirabellensaft** [oovm/circle-packing#1]
Hi! 

I wanted to use your crate circle in my project, but need to write an extension for your crate. I followed the link on docs.rs and crates.io and found this empty project. Are you still the owner of the crate? I would love to use it, can you point me where to find it?

Mirabellensaft

**Comment by oovm** [comment]
Sorry for late, I spent a while looking for my old computer.

The local branch has not been published.

**Comment by oovm** [comment]
This definition focuses on floating point numbers.

https://github.com/oovm/circle-packing/blob/13a298d6c728c1d472a91f9b3749205ad56d6abc/projects/circle/src/lib.rs#L28-L33


And the generic version is in:

https://github.com/oovm/shape-rs/blob/577480906f0407aa8ec08e40eafee7aab6a19720/projects/shape-core/src/elements/ellipses/mod.rs#L11-L16
